version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: AET_HITS
    ports:
      - "15432:5432"
    networks:
      - my-network
  user-app:
    build:
      context: user-app
      dockerfile: Dockerfile
    container_name: users
    depends_on:
      - db
      - kafka
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/AET_HITS
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - my-network
  notification:
    build:
      context: notification-app
      dockerfile: Dockerfile
    container_name: notification
    hostname: notification-app
    depends_on:
      - db
      - kafka
      - user-app
      - doc-core
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/AET_HITS
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - my-network
  doc-core:
    container_name: doc-core
    build:
      context: doc-core
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - db
      - kafka
      - user-app
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/AET_HITS
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - my-network
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_MESSAGE_MAX_BYTES=33554432
    networks:
      - my-network
  front:
    build:
      context: Front-end_mothers_dev
      dockerfile: Dockerfile
    container_name: front
    ports:
      - '5000:3000'
    depends_on:
      - user-app
      - doc-core
      - notification
    environment:
      - REACT_APP_API_URL=84.201.140.78
    networks:
      - my-network
volumes:
  db_data:
networks:
  my-network:
    driver: bridge