server:
  port: 8084
spring:
  liquibase:
    enabled: false
  application:
    name: notification-app
  datasource:
    url: jdbc:postgresql://localhost:5432/AET_HITS
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: forumhits968@gmail.com
    password: "assp hbnn weja xnhw"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

spring.config.import: classpath:/security-config.yml